#! /usr/bin/perl -w
#
# Copyright (c) 2018 Ron R Wills <ron.rwsoft@gmail.com>
#
# This file is part of Meat.
#
# Meat is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Meat is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Meat.  If not, see <http://www.gnu.org/licenses/>.
#
#==============================================================================
#
#  I'm not a fan of Perl but this is what Perl does best. When a class is
# loaded in the Meat virtual machine, meat doesn't allow the class to be
# replaced. Therefore, we can't use Grinder to create the Grinder classes.
# Because of this we play some games. We add the ᶲ unicode character to the
# names to avoid class name collisions, but this makes the c++ code generated
# incorrect. This is where this script comes in ;)
#
#  To create the src/Grinder.cpp file completely by hand would be a absolute
# nightmare so we want Grinder to do it. What we get from grinder.meat isn't
# quite usable and takes some work to make it usable. This script does that
# work for us and lets us maintain the code in the grinder.meat file.
#
# $ cp ../lib/Grinder.cpp ../lib/Grinder.cpp.bak
# $ make test
# $ ./fix-grinder.pl grinder.cpp > ../lib/Grinder.cpp
#
#  Now build the software. If it doesn't build the differences can be checked
# between the backup and the newly generated file.
#
# *** DON'T MAKE THE ASSUMTION THIS SCRIPT WORKS 100% OF THE TIME ***
# ***         MAKE BACKUPS AND DOUBLE CHECK THE RESULTS           ***

%hash_trans = ();

sub translate_hashes {
		foreach $name (@_) {
				# Get the hash value that will be found in the code.
				open(GRINDER_FH, "../bin/meat-grinder -# $nameᶲ |");
				local $old_hash = <GRINDER_FH>;
				chomp $old_hash;
				close(GRINDER_FH);

				# Get the new hash value we need in the code.
				open(GRINDER_FH, "../bin/meat-grinder -# $name |");
				local $new_hash = <GRINDER_FH>;
				chomp $new_hash;
				close(GRINDER_FH);

				$hash_trans{$old_hash} = $new_hash;
		}
}

###############################################################################
#  Get all the class name hashes with and without the ᶲ unicode character in
# the name.

translate_hashes("Grinder.SyntaxException", "Grinder.Library",
                 "Grinder.Class", "Grinder.Method");

###############################################################################
#  Remove the ᶲ unicode character in the names and fix all the class name
# hashes in the virtual tables.

local $/;
$cpp = <>;

$cpp =~ s/ᶲ//g;

while (($key, $value) = each(%hash_trans)) {
		$cpp =~ s/$key/$value/g;
}

###############################################################################
# Replace the header with the GPL header.

$header = '\/\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
 \* Auto-generated by the Grinder Compiler Library
 \*\/';

$gpl = '/*                                                                  -*- c++ -*-
 * The Meat language builtin classes.
 *
 * Copyright (c) 2017 Ron R Wills <ron.rwsoft@gmail.com>
 *
 * This file is part of Meat.
 *
 * Meat is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Meat is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Meat.  If not, see <http://www.gnu.org/licenses/>.
 *
 * This file should not be modified directly. It is generated from the
 * grinder.meat found in the tests directory. Make any modification to the
 * tests/grinder.meat file, do a make test and use the tests/fix-grinder.pl
 * script to regenerate this file.
 *
 * This might seem like a chore but it sure beats maintaining this code by
 * hand ;)
 */';

$cpp =~ s/$header/$gpl/mg;

###############################################################################
#  Replace the library loading function definition with the meat::initialize
# function definition.

$cpp =~ s/init_grinder/init_Grinder/g;

###############################################################################
# Dump the results...

print $cpp;
